const LOGIN_INTERPRETER_PROGRESS = 'LOGIN_INTERPRETER_PROGRESS'
const LOGIN_INTERPRETER_SUCCESS  = 'LOGIN_INTERPRETER_SUCCESS'
const LOGIN_INTERPRETER_FAILURE = 'LOGIN_INTERPRETER_FAILURE'

const REGISTER_INTERPRETER_PROGRESS = 'REGISTER_INTERPRETER_PROGRESS'
const REGISTER_INTERPRETER_SUCCESS = 'REGISTER_INTERPRETER_SUCCESS'
const REGISTER_INTERPRETER_FAILURE = 'REGISTER_INTERPRETER_FAILURE'

const RESET_PASS_INTERPRETER_PROGRESS = 'RESET_PASS_INTERPRETER_PROGRESS'
const RESET_PASS_INTERPRETER_SUCCESS = 'RESET_PASS_INTERPRETER_SUCCESS'
const RESET_PASS_INTERPRETER_FAILURE = 'RESET_PASS_INTERPRETER_FAILURE'

export default{
    LOGIN_INTERPRETER_PROGRESS,
    LOGIN_INTERPRETER_SUCCESS,
    LOGIN_INTERPRETER_FAILURE,

    REGISTER_INTERPRETER_PROGRESS,
    REGISTER_INTERPRETER_SUCCESS,
    REGISTER_INTERPRETER_FAILURE,

    RESET_PASS_INTERPRETER_PROGRESS,
    RESET_PASS_INTERPRETER_SUCCESS,
    RESET_PASS_INTERPRETER_FAILURE
}

export const LOG_IN = 'LOG_IN'
export const EMAIL_VERIFY = 'EMAIL_VERIFY'
export const DASHBOARD = 'DASHBOARD'
