const LOGIN_CLIENT_PROGRESS = 'LOGIN_CLIENT_PROGRESS'
const LOGIN_CLIENT_SUCCESS  = 'LOGIN_CLIENT_SUCCESS'
const LOGIN_CLIENT_FAILURE = 'LOGIN_CLIENT_FAILURE'

const REGISTER_CLIENT_PROGRESS = 'REGISTER_CLIENT_PROGRESS'
const REGISTER_CLIENT_SUCCESS = 'REGISTER_CLIENT_SUCCESS'
const REGISTER_CLIENT_FAILURE = 'REGISTER_CLIENT_FAILURE'

const RESET_PASS_PROGRESS = 'RESET_PASS_PROGRESS'
const RESET_PASS_SUCCESS = 'RESET_PASS_SUCCESS'
const RESET_PASS_FAILURE = 'RESET_PASS_FAILURE'

export default{
    LOGIN_CLIENT_PROGRESS,
    LOGIN_CLIENT_SUCCESS,
    LOGIN_CLIENT_FAILURE,

    REGISTER_CLIENT_PROGRESS,
    REGISTER_CLIENT_SUCCESS,
    REGISTER_CLIENT_FAILURE,

    RESET_PASS_PROGRESS,
    RESET_PASS_SUCCESS,
    RESET_PASS_FAILURE
}
